/**
 * @packageDocumentation
 * @module api.functional.email
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { EmailController } from "../../../controllers/email/EmailController";

export * as google from "./google";

/**
 * Send an email.
 *
 * This endpoint accepts recipient, subject (optional), and message body
 * and sends a simple HTML email using Gmail connector.
 * @controller EmailController.send
 * @path POST /email/send
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function send(
  connection: IConnection,
  input: send.Body,
): Promise<send.Output> {
  return true === connection.simulate
    ? send.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...send.METADATA,
          template: send.METADATA.path,
          path: send.path(),
        },
        input,
      );
}
export namespace send {
  export type Body = EmailController.ISendInput;
  export type Output = EmailController.ISendOutput;

  export const METADATA = {
    method: "POST",
    path: "/email/send",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/email/send";
  export const random = (): EmailController.ISendOutput =>
    typia.random<EmailController.ISendOutput>();
  export const simulate = (connection: IConnection, input: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random();
  };
}
